### ISSUE TITLE
Add promise-ftp-common as a dependency

### ISSUE THREAD

**Issue by Scimonster** [realtymaps/promise-ftp#12]
I don't see a real reason to have this as a peer dependency. It makes it harder for me to include the library in my app (i want to just install and not have to worry about installing something else). If someone is using both this and the SFTP module, so they can just run `npm dedupe` to limit the storage space, if that's a concern.

**Comment by zacronos** [comment]
I understand where you are coming from, though there is a "real" reason to have the peer dependency.  If someone is using both the `promise-ftp` and `promise-sftp` modules, `PromiseFtp.FtpConnectionError != PromiseSftp.FtpConnectionError` if `promise-ftp-common` is a separate dependency of each module.  This is counterintuitive and can lead to unexpected bugs.

This sort of situation is solved by peer dependencies.  Unfortunately, npm 3.x decided not to install peer dependencies automatically, which has made it an annoying feature to make use of.

As an alternative, I can do as you are suggesting and make `promise-ftp-common` a regular dependency for each module, and include in the documentation about the `PromiseFtp.FtpConnectionError != PromiseSftp.FtpConnectionError` problem and how to fix it.  My mindset is to prefer to have a problem that is blatant (such as the entire module not working unless you install `promise-ftp-common`) rather than subtle and hard to debug (such as `PromiseFtp.FtpConnectionError != PromiseSftp.FtpConnectionError` unless you install `promise-ftp-common`).

But, since most people are probably not using moth modules in a way where the subtle issue will be a problem, I am questioning whether I should find a better way to approach this problem.

Actually, I looked around, and found this blog article that seems to propose a great solution: https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/

I will add `promise-ftp-common` as both a dependency **and** a peerDependency.  This solves both the install and the counter-intuitive problems, at the cost of double-installing the dependency under npm 2.x.  `promise-ftp-common` is tiny and so I expect this won't be an issue for 99.9% of apps, and for those where this is a problem `npm dedupe` is the solution they should already be using anyway.

**Comment by zacronos** [comment]
This should be handled as of v1.3.2
